name: torch
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py38_1001
  - argon2-cffi=20.1.0=py38haf1e3a3_1
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38hed5b41f_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=h18a8e69_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=hb1e8313_2
  - freetype=2.10.2=ha233b18_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.66.1=h9bbe63b_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=py_0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.2.0=py38h04f5b5a_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=haf1e3a3_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.13.0.1=hab81aa3_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.1.0=hcb84e12_1
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h0a44026_0
  - markupsafe=1.1.1=py38h1de35cc_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h5670ca0_0
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - more-itertools=8.5.0=py_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.1=py_0
  - ninja=1.9.0=py38h04f5b5a_0
  - notebook=6.1.4=py38_0
  - numpy-base=1.18.5=py38h3304bdc_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py38h959d312_0
  - pandoc=2.11=h0dc7051_0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py38_1
  - pickleshare=0.7.5=py38_1001
  - pillow=7.1.2=py38h4655f20_0
  - pip=20.1.1=py38_1
  - pluggy=0.13.1=py38_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=py38_0
  - py=1.9.0=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.2=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.17.3=py38haf1e3a3_0
  - pytest=6.1.1=py38_0
  - python=3.8.3=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyzmq=19.0.2=py38hb1e8313_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.23.1=py38h603561c_0
  - send2trash=1.5.0=py38_0
  - setuptools=47.3.1=py38_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=hffcf06c_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py38h1de35cc_1
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h1990bb4_3
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.7.2
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - ase==3.20.1
    - async-timeout==3.0.1
    - ax-platform==0.1.18
    - beautifulsoup4==4.9.3
    - blessings==1.7
    - boltons==20.2.1
    - botorch==0.3.2
    - cachetools==4.1.0
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.4
    - colorful==0.5.4
    - decorator==4.4.2
    - dgl==0.4.3.post2
    - et-xmlfile==1.0.1
    - filelock==3.0.12
    - future==0.18.2
    - google==3.0.0
    - google-api-core==1.23.0
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.52.0
    - googledrivedownloader==0.4
    - gpustat==0.6.0
    - gputil==1.4.0
    - gpytorch==1.2.1
    - grpcio==1.30.0
    - h5py==2.10.0
    - hiredis==1.1.0
    - idna==2.10
    - isodate==0.6.0
    - jdcal==1.4.1
    - littleutils==0.2.2
    - llvmlite==0.34.0
    - markdown==3.2.2
    - msgpack==1.0.0
    - multidict==5.0.0
    - networkx==2.4
    - numba==0.51.2
    - numpy==1.19.3
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - ogb==1.2.4
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - openpyxl==3.0.5
    - outdated==0.2.0
    - plotly==4.12.0
    - protobuf==3.12.2
    - psutil==5.7.3
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pykeops==1.4.1
    - pytorch-lightning==0.8.1
    - ray==1.0.0
    - rdflib==5.0.0
    - redis==3.4.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scipy==1.5.0
    - soupsieve==2.0.1
    - sqlalchemy==1.3.20
    - tabulate==0.8.7
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - torch==1.6.0
    - torch-geometric==1.6.1
    - torch-scatter==2.0.5
    - torch-sparse==0.6.7
    - torchdiffeq==0.1.1
    - torchsde==0.2.1
    - torchsummary==1.5.1
    - torchvision==0.7.0
    - tqdm==4.46.1
    - trampoline==0.1.2
    - typeguard==2.10.0
    - typing-extensions==3.7.4.3
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - yarl==1.6.2
prefix: /Users/bchamberlain/anaconda3/envs/torch

