name: graph-neural-pde
channels:
  - soumith
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cycler=0.10.0
  - freetype=2.10.4
  - intel-openmp=2020.2
  - joblib=1.0.0
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numba=0.50.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.3.3
  - pyparsing=2.4.7
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.7.1
  - readline=8.0
  - setuptools=51.1.2
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2020.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchvision=0.2.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - ase==3.20.1
    - boltons==20.2.1
    - chardet==4.0.0
    - decorator==4.4.2
    - et-xmlfile==1.0.1
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - idna==2.10
    - isodate==0.6.0
    - jdcal==1.4.1
    - jinja2==2.11.2
    - littleutils==0.2.2
    - llvmlite==0.33.0
    - markupsafe==1.1.1
    - networkx==2.5
    - ogb==1.2.4
    - openpyxl==3.0.6
    - outdated==0.2.0
    - pandas==1.2.0
    - pykeops==1.4.2
    - python-louvain==0.15
    - pytz==2020.5
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.0
    - scipy==1.5.4
    - torch-cluster==1.5.8
    - torch-geometric==1.6.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - torchdiffeq==0.1.1
    - torchsde==0.2.4
    - tqdm==4.56.0
    - trampoline==0.1.2
    - urllib3==1.26.2
prefix: /Users/benchamberlain/anaconda/envs/graph-neural-pde
